name: Build
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build plugins
        run: |
          chmod +x gradlew
          ./gradlew make generateUpdaterJson -Dorg.gradle.jvmargs="-Xmx12g -XX:+UseParallelGC" -Dorg.gradle.vfs.watch=false

          install -D -t builds plugins/*/build/outputs/*.zip build/outputs/updater.json

      - name: Publish plugins
        working-directory: builds
        run: |
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote add origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}"
          git fetch --depth 1 --filter=blob:none origin builds || false && git reset FETCH_HEAD

          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push origin HEAD:builds
